version: '3'
services:
  mydocuments:
    image: ghcr.io/pama-lee/my_documents:latest
    ports:
      - "20001:8080"
    volumes:
      - mydocuments-config:/root/config
      - mydocuments-files:/root/files
volumes:
  mydocuments-config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/my_documents/config
  mydocuments-files:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/my_documents/files